nodeLinker: node-modules

enableGlobalCache: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

packageExtensions:
  "@mui/material@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "react-scripts@*":
    peerDependencies:
      typescript: "*"

yarnPath: ../.yarn/releases/yarn-4.6.0.cjs 