nodeLinker: node-modules
enableGlobalCache: true
enableScripts: true
enableTelemetry: false
networkTimeout: 100000

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

packageExtensions:
  "@mui/material@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "react-scripts@*":
    peerDependencies:
      typescript: "*"
  "eslint-config-react-app@*":
    peerDependencies:
      typescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
