enableGlobalCache: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@mui/material@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  eslint-config-react-app@*:
    peerDependencies:
      typescript: "*"
  react-scripts@*:
    peerDependencies:
      typescript: "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
